name: Fetch Live KML Data

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and clean KML data
        run: |
          set -euo pipefail
          # Step 1: Download the file
          curl -fL --retry 3 --retry-delay 5 --connect-timeout 15 \
            -o live_data.kml "https://theowl.pildo.com/foreflight/foreFlightKml/adsb?token=xrrbezzrik1749035639392"
            
          # 👇 Step 2: Find and replace the problematic folder name
          sed -i 's/ESHB - Östra Hospital/ESHB - Ostra Hospital/g' live_data.kml

          # Step 3: Basic sanity checks
          test -s live_data.kml
          grep -qi "<kml" live_data.kml || { echo "Downloaded file doesn't look like KML"; exit 1; }

      - name: Create KMZ archive (fresh)
        run: |
          set -euo pipefail
          rm -f live_data.kmz
          zip -X -j -9 live_data.kmz live_data.kml
          zip -T live_data.kmz

      - name: Commit and push if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add live_data.kmz
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Automated KML data update"
            git push
          fi