name: Fetch Live KML Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and Clean KML
        run: |
          set -euo pipefail
          
          # Step 1: Download the KML file
          echo "Downloading KML data..."
          curl -fL --retry 3 --retry-delay 5 --connect-timeout 15 \
            -o live_data.kml "https://theowl.pildo.com/foreflight/foreFlightKml/adsb?token=xrrbezzrik1749035639392"
          
          # Step 2: Convert the file's encoding from ISO-8859-1 to UTF-8
          echo "Converting file encoding to UTF-8..."
          iconv -f ISO-8859-1 -t UTF-8 -o live_data_utf8.kml live_data.kml
          mv live_data_utf8.kml live_data.kml
          
          # Step 3: Globally replace all instances of 'Östra' with 'Ostra'
          echo "Performing global text replacement..."
          sed -i 's/Östra/Ostra/g' live_data.kml
          
          # Step 4: Verify the change was made (optional but good practice)
          echo "Verifying changes..."
          if grep -q "Ostra" live_data.kml; then
            echo "Success: 'Ostra' was found in the modified file."
          else
            echo "ERROR: Could not find 'Ostra' after replacement."
            exit 1
          fi

      - name: Create KMZ archive (fresh)
        run: |
          set -euo pipefail
          rm -f live_data.kmz
          # The -j flag junks paths, storing only the filename inside the zip
          zip -j -X -9 live_data.kmz live_data.kml
          zip -T live_data.kmz

      - name: Commit and push if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add live_data.kmz
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Automated KML data update"
            git push
          fi