name: Fetch Live KML Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch KML data from source
        run: |
          set -euo pipefail
          curl -fL --retry 3 --retry-delay 5 --connect-timeout 15 \
            -o live_data.kml "https://theowl.pildo.com/foreflight/foreFlightKml/adsb?token=xrrbezzrik1749035639392"
          # Basic sanity checks: non-empty and looks like KML
          test -s live_data.kml
          grep -qi "<kml" live_data.kml || { echo "Downloaded file doesn't look like KML"; exit 1; }

      - name: Create KMZ archive (fresh)
        run: |
          set -euo pipefail
          rm -f live_data.kmz                 # <-- critical: remove any existing invalid/corrupt file
          # -X strips extra attrs to reduce noisy diffs; -j stores just the file, -9 max compression
          zip -X -j -9 live_data.kmz live_data.kml
          # Verify the archive structure
          zip -T live_data.kmz

      - name: Commit and push if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add live_data.kmz
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Automated KML data update"
            git push
          fi
