name: Fetch Live KML Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch, Clean, and Verify KML
        run: |
          set -euo pipefail
          
          # Step 1: Install xmlstarlet, a tool for editing XML/KML files
          echo "Installing xmlstarlet..."
          sudo apt-get update > /dev/null
          sudo apt-get install -y xmlstarlet > /dev/null
          echo "Installation complete."

          # Step 2: Download the KML file
          echo "Downloading KML data..."
          curl -fL --retry 3 --retry-delay 5 --connect-timeout 15 \
            -o live_data.kml "https://theowl.pildo.com/foreflight/foreFlightKml/adsb?token=xrrbezzrik1749035639392"
          
          # Step 3: DEBUG - Show the line before we change it
          echo "--- Content BEFORE modification ---"
          grep "Östra" live_data.kml || echo "The string 'Östra' was not found in the original file."
          echo "---------------------------------"

          # Step 4: Use xmlstarlet to find the <name> tag containing 'Östra' and update its value
          echo "Attempting to modify the KML file with xmlstarlet..."
          xmlstarlet ed --inplace -u "//Folder/name[contains(text(),'Östra')]" -v "ESHB - Ostra Hospital" live_data.kml
          
          # Step 5: DEBUG - Verify the change was made
          echo "--- Content AFTER modification ---"
          grep "Ostra" live_data.kml || echo "ERROR: The new string 'Ostra' was not found after modification."
          echo "--------------------------------"

      - name: Create KMZ archive (fresh)
        run: |
          set -euo pipefail
          rm -f live_data.kmz
          zip -X -j -9 live_data.kmz live_data.kml
          zip -T live_data.kmz

      - name: Commit and push if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add live_data.kmz live_data.kml
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Automated KML data update"
            git push
          fi